services:
  mongo:
    image: mongo:8

    container_name: mongodb

    ports:
      - "27007:27017"

    volumes:
      - mongo_data:/data/db


    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    restart: always

    networks:
      - back

  qdrant:
    image: qdrant/qdrant:v1.13.6
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - back
    restart: always


networks:
  back:

volumes:
  mongo_data:
  qdrant_data: