import time

from fastapi import FastAPI, Request
from prometheus_client import Counter, Histogram, make_asgi_app
from starlette.middleware.base import BaseHTTPMiddleware

# ============================================================
# HTTP metrics
# ============================================================

REQUEST_COUNT = Counter(
    "http_requests_total",
    "Total number of HTTP requests.",
    ["method", "endpoint", "status"],
)


REQUEST_LATENCY = Histogram(
    "http_request_duration_seconds",
    "HTTP request duration in seconds.",
    ["method", "endpoint"],
)


# ============================================================
# RAG indexing metrics
# ============================================================

INDEXING_BATCHES = Counter(
    "rag_indexing_batches_total",
    "Total number of successfully indexed batches.",
)


INDEXING_CHUNKS = Counter(
    "rag_indexing_chunks_total",
    "Total number of successfully indexed chunks.",
)


INDEXING_FAILURES = Counter(
    "rag_indexing_failures_total",
    "Total number of failed indexing operations.",
)


INDEXING_DURATION = Histogram(
    "rag_indexing_duration_seconds",
    "Time spent indexing a project.",
)


EMBEDDING_DURATION = Histogram(
    "rag_embedding_duration_seconds",
    "Time spent generating embeddings during indexing.",
)


VECTOR_STORE_DURATION = Histogram(
    "rag_vector_store_duration_seconds",
    "Time spent storing vectors during indexing.",
)

# ============================================================
# RAG retrieval metrics
# ============================================================

RETRIEVAL_REQUESTS = Counter(
    "rag_retrieval_requests_total",
    "Total number of retrieval requests.",
)


RETRIEVAL_RESULTS = Counter(
    "rag_retrieval_results_total",
    "Total number of successfully retrieved chunks.",
)


RETRIEVAL_FAILURES = Counter(
    "rag_retrieval_failures_total",
    "Total number of failed retrieval operations.",
)


RETRIEVAL_DURATION = Histogram(
    "rag_retrieval_duration_seconds",
    "Time spent executing a retrieval operation.",
)


RETRIEVAL_EMBEDDING_DURATION = Histogram(
    "rag_retrieval_embedding_duration_seconds",
    "Time spent generating the query embedding during retrieval.",
)


RETRIEVAL_VECTOR_SEARCH_DURATION = Histogram(
    "rag_retrieval_vector_search_duration_seconds",
    "Time spent searching the vector database during retrieval.",
)

# ============================================================
# RAG generation metrics
# ============================================================

GENERATION_REQUESTS = Counter(
    "rag_generation_requests_total",
    "Total number of generation requests.",
)


GENERATION_FAILURES = Counter(
    "rag_generation_failures_total",
    "Total number of failed generation operations.",
)


GENERATION_NO_CONTEXT = Counter(
    "rag_generation_no_context_total",
    "Total number of generation requests with no relevant context.",
)


GENERATION_DURATION = Histogram(
    "rag_generation_duration_seconds",
    "Time spent executing the full RAG generation operation.",
)


PROMPT_BUILD_DURATION = Histogram(
    "rag_prompt_build_duration_seconds",
    "Time spent building the generation prompt.",
)


LLM_GENERATION_DURATION = Histogram(
    "rag_llm_generation_duration_seconds",
    "Time spent generating the answer with the chat model.",
)

# ============================================================
# LLM token usage metrics
# ============================================================

LLM_INPUT_TOKENS = Counter(
    "rag_llm_input_tokens_total",
    "Total number of input tokens processed by chat models.",
    ["provider", "model"],
)


LLM_OUTPUT_TOKENS = Counter(
    "rag_llm_output_tokens_total",
    "Total number of output tokens generated by chat models.",
    ["provider", "model"],
)


LLM_TOTAL_TOKENS = Counter(
    "rag_llm_total_tokens_total",
    "Total number of input and output tokens processed by chat models.",
    ["provider", "model"],
)

# ============================================================
# HTTP middleware
# ============================================================


class PrometheusMiddleware(BaseHTTPMiddleware):
    async def dispatch(
        self,
        request: Request,
        call_next,
    ):
        if request.url.path == "/metrics":
            return await call_next(request)

        start_time = time.perf_counter()

        try:
            response = await call_next(request)

        except Exception:
            duration = time.perf_counter() - start_time

            route = request.scope.get("route")
            endpoint = getattr(
                route,
                "path",
                request.url.path,
            )

            REQUEST_LATENCY.labels(
                method=request.method,
                endpoint=endpoint,
            ).observe(duration)

            REQUEST_COUNT.labels(
                method=request.method,
                endpoint=endpoint,
                status="500",
            ).inc()

            raise

        duration = time.perf_counter() - start_time

        route = request.scope.get("route")
        endpoint = getattr(
            route,
            "path",
            request.url.path,
        )

        REQUEST_LATENCY.labels(
            method=request.method,
            endpoint=endpoint,
        ).observe(duration)

        REQUEST_COUNT.labels(
            method=request.method,
            endpoint=endpoint,
            status=str(response.status_code),
        ).inc()

        return response


def setup_metrics(app: FastAPI) -> None:
    app.add_middleware(PrometheusMiddleware)

    metrics_app = make_asgi_app()

    app.mount(
        "/metrics",
        metrics_app,
    )
